config/routes.rb
SimpleBlog::Application.routes.draw do

  root to: 'articles#index'

  resources :articles do
    resources :comments, only: [:create, :destroy]  
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :body,:title, :presence => true
  attr_accessible :body, :title
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  attr_accessible :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_last_action
  after_filter 	:flash_time


  private
  def set_last_action
  	session[:last_action] = Time.now.strftime("%r")
  end
  def flash_time
  	flash[:notice] = session[:last_action]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :load_article
  before_filter :load_articles_with_caps, :only => [:index]

  # GET /articles
  # GET /articles.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  private
  def load_article
    @article = Article.find(params[:id]) if params[:id]
  end

  def load_articles_with_caps
    @articles = Article.all
    @articles.each {|article| article.title = article.title.titleize }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  # POST /comments.json
  before_filter :make_happy_comment, :only => :create

  def create
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to @comment.article }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @comment.article }
      format.json { head :no_content }
    end
  end
  private
  def make_happy_comment
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(params[:comment])
    @comment.body.gsub!(/sad/,'happy')
    @comment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: 'span5' %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, rows: 12, class: 'span10' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Editing article</h2>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="article">
    <h3><%= article.title %></h3>
    <p>
      <%= raw truncate(article.body, length: 200, separator: '...') %>
      <br>
      <%= link_to 'Show', article %> |
      <%= link_to 'Edit', edit_article_path(article) %> |
      <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
<% end %>

app/views/articles/new.html.erb
<h2>New article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @article.title %>
</h2>

<%= raw @article.body %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<hr>
<div class="row">
  <div class="comments span8">
    <h4>Comments</h4>

    <%= render @article.comments %>

    <%= render 'comments/form' %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="comment well well-small">
  <%= raw comment.body %>

  <small style="display: block; text-align: right;">
    <i>Posted on: <%= comment.created_at %></i> | 
    <%= link_to 'Destroy', article_comment_path(comment.article, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
  </small>
</div>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment = Comment.new] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, rows: 2, class: 'span8' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<h1>Simple Blog</h1>     
<div class="row"> 
  <div class="span4 offset8">
    <span class="pull-right">
      <%= link_to 'New Article', new_article_path, class: 'btn' %>
    </span>
  </div>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--   <div>
  	<h2>Debug Info</h2>
  	<p><%= session.inspect %></p>
  </div> -->
	<% if flash[:notice] %>
	  <p class="notice">Last action:<%= flash[:notice] %></p>
	<% end %>
  <div class="container">
    <%= render 'layouts/header' %>

    <%= yield %>
  </div>

</body>
</html>